### ISSUE TITLE
Solve this after Issue #2. Update the README.md file with the new screenshots names

### ISSUE THREAD

**Issue by vanquisher1234567** [rdorkadi/e-jotter#3]
## This is the old one, but now you have to change here with the new screenshot names in README.md file

<img width="1047" alt="Screenshot 2024-02-16 at 5 46 48 PM" src="https://github.com/rdorkadi/e-jotter/assets/154570373/cdd99450-7ec4-485c-b641-cc53920b8687">

**Comment by rdorkadi** [comment]
updated
